# -*- coding: utf-8 -*-
"""gradientdescent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_5i9eTA-85nMT41zfCDp3mpOYalr-De

**Gradient Descent**: It is an optimization algorithm that minimizes loss function by iteratively updating parameters in the direction of negative gradient.
"""

import numpy as np

X = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,9])

learning_rate = 0.01
m = 0
b = 0
epochs = 1000
n = len(X)

for i in range(epochs):
  y_pred = m * X + b
  dm = (-2/n)*np.sum(X*(y-y_pred))
  db = (-2/n)*np.sum(y-y_pred)

  m = m - learning_rate*dm
  b = b - learning_rate*db

  if i%100==0:
    mse = np.mean((y-y_pred)**2)
    print(f"Epoch: {i} MSE: {mse}")

print("\nFinal values:")
print("m: ",m)
print("b: ",b)