# -*- coding: utf-8 -*-
"""logisticregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYsVyf0C0JvH8IPte6ot9UwLZnNh-_-b
"""

import numpy as np

X = np.array([1,2,3,4,5])
X = X / np.max(X)
y = np.array([0,0,0,1,1])

m = 0
b = 0
learning_rate = 0.05
epochs = 5000
n = len(X)

def sigmoid(z) :
  return 1/(1 + np.exp(-z))

for i in range(epochs) :
  z = m * X + b
  y_pred = sigmoid(z)

  loss = -np.mean(y*np.log(y_pred+ 1e-9) + (1-y)*np.log(1-y_pred+ 1e-9))

  dm = (1/n)*np.sum((y-y_pred)*X)
  db = (1/n)*np.sum((y-y_pred))

  m = m + learning_rate*dm
  b = b + learning_rate*db

  if i%100==0:
    print(f"Epochs: {i}, Loss: {loss}")

print("\nFinal values:")
print("m: ",m)
print("b: ",b)

y_pred = sigmoid(m * X + b)
print("Probabilities:", y_pred)

y_class = [1 if i >= 0.5 else 0 for i in y_pred]
print("Predicted classes:", y_class)

import numpy as np
import matplotlib.pyplot as plt

plt.scatter(X,y)
X_line = np.linspace(0,1,100)
y_line = 1/(1 + np.exp(-(m*X_line+b)))
plt.plot(X_line, y_line)
boundary = -b / m
plt.axvline(x=boundary)
plt.show()