# -*- coding: utf-8 -*-
"""neuralnetwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YcqTUDrjSFJAUYQTkPSphnzDWAKzeh5
"""

import torch

x = torch.tensor([1.0, 2.0, 3.0])
print(x)

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a+b)
print(a*b)

"""## First Neural Network"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(1,8),
    nn.ReLU(),
    nn.Linear(8,1)
)

"""##Training

"""

X = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y = torch.tensor([[2.0],[4.0],[6.0],[8.0]])

loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(1000):
  y_pred = model(X)
  loss = loss_fn(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print(epoch, loss.item())

print(model(torch.tensor([[5.0]])))